#pragma config(Motor,  port1,           leftTop,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftMid,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftBot,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightTop,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightMid,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightBot,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           rightDrive,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port9,           leftClaw,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightClaw,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void driveDecimal(float times, float right, float left)
	{
		motor[leftDrive]=left*127;
		motor[rightDrive]=right*127;
		wait1Msec (times);
		motor[leftDrive]=0;
		motor[rightDrive]=0;
	}
void fireDec(float f)
	{
		motor[leftTop] = 127*f;
		motor[leftMid]= 127*f;
		motor[leftBot] = 127*f;
		motor[rightTop]= -127*f;
		motor[rightMid]= -127*f;
		motor[rightBot] = -127*f;
		wait1Msec (3000);
		motor[leftTop] = -127;
		motor[leftMid]= -127;
		motor[leftBot] = -127;
		motor[rightTop]= 127;
		motor[rightMid]= 127;
		motor[rightBot] = 127;
		wait1Msec(3000);
		motor[leftTop] = 0;
		motor[leftMid]= 0;
		motor[leftBot] = 0;
		motor[rightTop]= 0;
		motor[rightMid]= 0;
		motor[rightBot] = 0;
	}
void clawBoolean(float timeA, bool OoC)
	{
		float np=1;
		if(OoC==false)
		{
			np=-1;
		}
		motor[leftClaw]=np*63;
		motor[rightClaw]=np*63;
		wait1Msec (timeA);
		motor[leftClaw]=0;
		motor[rightClaw]=0;
	}
void turnBot(float turn)
	{
		motor[leftDrive] = -turn*127;
		motor[rightDrive] = turn*127;
	}
	/*
	Sam's Practice Code	*/
	task autonomous()
	{
	driveDecimal(1000,.2,-.2);
	clawBoolean(750,true);
	driveDecimal(1000,1,1);
	clawBoolean(750,false);
	fireDec(.75);
  turnBot(0);
	}
task main()
{
	startTask(autonomous);


/*


	while(true)
	{
		tankControl(Ch2, Ch3);
		if(vexRT(Btn6D)==1)
		{
			motor[leftTop] = 127;
			motor[leftMid]= 127;
			motor[leftBot] = 127;
			motor[rightTop]= -127;
			motor[rightMid]= -127;
			motor[rightBot] = -127;
		}
		else if(vexRT(Btn6U)==1)
		{
			motor[leftTop] = -127;
			motor[leftMid]= -127;
			motor[leftBot] = -127;
			motor[rightTop]= 127;
			motor[rightMid]= 127;
			motor[rightBot] = 127;
		}
		else
		{
			motor[leftTop] = 0;
			motor[leftMid]= 0;
			motor[leftBot] = 0;
			motor[rightTop]= 0;
			motor[rightMid]=0;
			motor[rightBot] = 0;
		}
		if(vexRT(Btn5D)==1)
		{
			motor[leftClaw]=63;
			motor[rightClaw]=63;
		}
		else if(vexRT(Btn5U)==1)
		{
			motor[leftClaw]=-63;
			motor[rightClaw]=-63;
		}
		else
		{
			motor[leftClaw]=0;
			motor[rightClaw]=0;
		}
	}*/
}










//Ends Here




																																																																															/*We're no strangers to love
																																																																															You know the rules and so do I
																																																																															A full commitment's what I'm thinking of
																																																																															You wouldn't get this from any other guy
																																																																															I just want to tell you how I'm feeling
																																																																															Gotta make you understand
																																																																															Never gonna give you up, never gonna let you down
																																																																															Never gonna run around and desert you
																																																																															Never gonna make you cry, never gonna say goodbye
																																																																															Never gonna tell a lie and hurt you
																																																																															We've known each other for so long
																																																																															Your heart's been aching but you're too shy to say it
																																																																															Inside we both know what's been going on
																																																																															We know the game and we're gonna play it
																																																																															And if you ask me how I'm feeling
																																																																															Don't tell me you're too blind to see
																																																																															Never gonna give you up, never gonna let you down
																																																																															Never gonna run around and desert you
																																																																															Never gonna make you cry, never gonna say goodbye*/
