#pragma config(Motor,  port1,           frontRight,    tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           backRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           threeRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           oneLeft,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           twoLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           threeLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           oneRight,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           twoRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}
void liftUp()
{
	motor[oneLeft]=127;
	motor[twoLeft]=127;
	motor[threeLeft]=127;
	motor[oneRight]=127;
	motor[twoRight]=127;
	motor[threeRight]=127;
}

void liftDown()
{
	motor[oneLeft]=-50;
	motor[twoLeft]=-50;
	motor[threeLeft]=-50;
	motor[oneRight]=-50;
	motor[twoRight]=-50;
	motor[threeRight]=-50;
}
void stopLift()
{
	motor[oneLeft]=0;
	motor[twoLeft]=0;
	motor[threeLeft]=0;
	motor[oneRight]=0;
	motor[twoRight]=0;
	motor[threeRight]=0;
}

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		tankControl(Ch3,Ch2);
		if(vexRT[Btn5U]==1)
		{
			liftDown();
		}
		else
		{
			stopLift();
		}

		if(vexRT[Btn6U]==1)
		{

			liftUp();
		}
		else
		{
			stopLift();
		}

	}
}
