#pragma config(Sensor, dgtl1,  dwnL,           sensorTouch)
#pragma config(Sensor, dgtl2,  dwnR,           sensorTouch)
#pragma config(Motor,  port1,           leftTop,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftMid,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftBot,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightTop,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightMid,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightBot,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           rightDrive,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port9,           leftClaw,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          strafing,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void off()
{
	motor[leftTop] = 0;
	motor[leftMid]= 0;
	motor[leftBot] = 0;
	motor[rightTop]= 0;
	motor[rightMid]= 0;
	motor[rightBot] = 0;
}

void driveDecimal(float times, float right, float left)
{
	motor[leftDrive]=left*127;
	motor[rightDrive]=right*127;
	wait1Msec (times);
	motor[leftDrive]=0;
	motor[rightDrive]=0;
}
void fireDec(float f)
{
	motor[leftTop] = -127*f;
	motor[leftMid]= -127*f;
	motor[leftBot] = -127*f;
	motor[rightTop]= 127*f;
	motor[rightMid]= 127*f;
	motor[rightBot] = 127*f;
	wait1Msec (000);

	motor[leftTop] = 0;
	motor[leftMid]= 0;
	motor[leftBot] = 0;
	motor[rightTop]= 0;
	motor[rightMid]= 0;
	motor[rightBot] = 0;

	motor[leftClaw]=-63;
	wait1Msec (1000);
	/*motor[leftTop] = 127;
	motor[leftMid]= 127;
	motor[leftBot] = 127;
	motor[rightTop]= -127;
	motor[rightMid]= -127;
	motor[rightBot] = -127;
	wait1Msec(1000);
	motor[leftTop] = 0;
	motor[leftMid]= 0;
	motor[leftBot] = 0;
	motor[rightTop]= 0;
	motor[rightMid]= 0;
	motor[rightBot] = 0;*/
}

void startlift()
{
	motor[leftTop] = -127;
	motor[leftMid]= -127;
	motor[leftBot] = -127;
	motor[rightTop]= 127;
	motor[rightMid]= 127;
	motor[rightBot] = 127;
	wait1Msec (270);
	motor[leftTop] = 0;
	motor[leftMid]= 0;
	motor[leftBot] = 0;
	motor[rightTop]= 0;
	motor[rightMid]= 0;
	motor[rightBot] = 0;
}

void clawBoolean(float timeA, bool OoC)
{
	float np=1;
	if(OoC==false)
	{
		np=-1;
	}
	motor[leftClaw]=np*63;
	wait1Msec (timeA);
	motor[leftClaw]=0;
}
task autonomous()
{

clawBoolean(10000,false);
	//time msec, open
	startlift();
	//lifts up the bar for .5 sec
	driveDecimal(1500,.6,.6);
	//time msec, right, left
	motor[leftClaw]=90;
	wait1Msec(1000);
	//time msec, close
	driveDecimal(1300,-.8,0);
	//time, right, left
	startlift();
	startlift();
	startlift();
	startlift();
	startlift();
	driveDecimal(2500,1,1);
	//time, right, left
	fireDec(1);
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}


task usercontrol()
{
	while(true)
	{



		tankControl(Ch2, Ch3);

		/////////Speed Control///////
		int speed= 115;
		int adjust=0;
		bool fast =true;
		if(vexRT(Btn8D)==1 && fast)
		{
			speed=75;
			fast=!fast;
		}
		if(vexRT(Btn8D)==1 && !fast)
		{
			speed=127;
			fast=!fast;
		}
		/////////Bar Lowering///////
		if(vexRT(Btn6D)==1)
		{
			motor[leftTop] = speed-adjust;
			motor[leftMid]= speed-adjust;
			motor[leftBot] = speed-adjust;
			motor[rightTop]= -speed;
			motor[rightMid]= -speed;
			motor[rightBot] = -speed;
		}
		/////////Bar Lifting///////
		else if(vexRT(Btn6U)==1)
		{
			motor[leftTop] = -speed+adjust;
			motor[leftMid]= -speed+adjust;
			motor[leftBot] = -speed+adjust;
			motor[rightTop]= speed;
			motor[rightMid]= speed;
			motor[rightBot] = speed;
		}
		else
		{
			motor[leftTop] = 0;
			motor[leftMid]= 0;
			motor[leftBot] = 0;
			motor[rightTop]= 0;
			motor[rightMid]=0;
			motor[rightBot] = 0;
		}
		/////////Claw Code////////
		if(vexRT(Btn5D)==1)
		{
			motor[leftClaw]=63;
			//motor[rightClaw]=63;
		}
		else if(vexRT(Btn5U)==1)
		{
			motor[leftClaw]=-63;
		}
		else
		{
			motor[leftClaw]=0;
		}
		//////Seperate Lift Lower Buttons///////
		if(vexRT(Btn8L)==1)
		{
			while(vexRT(Btn8L)==1)
			{
				motor[leftTop]= 127;
				motor[leftMid]= 127;
				motor[leftBot] = 127;
			}
			off();
		}
		if(vexRT(Btn8R)==1)
		{
			while(vexRT(Btn8R)==1)
			{
				motor[rightTop]= -127 +5;
				motor[rightMid]= -127 +5;
				motor[rightBot] = -127 +5;
			}
			off();
		}

		/////New Wheel Code

		if(vexRT(Btn7L)==1)
		{
			motor[strafing]=-127;
		}
		else if(vexRT(Btn7R)==1)
		{
			motor[strafing]=127;
		}
		else
		{
			motor[strafing]=0;
		}

		///////Expiremental Code/////

		//////Automatic Lift Reset///////
		//if(vexRT(Btn7D)==1)
		//{
		//	while(SensorValue(dwnR)==0 && SensorValue(dwnL)==0)
		//	{
		//		motor[leftTop] = -127;
		//		motor[leftMid]= -127;
		//		motor[leftBot] = -127;
		//		motor[rightTop]= 127;
		//		motor[rightMid]= 127;
		//		motor[rightBot] = 127;
		//	}
		//	off();
		//	while(SensorValue(dwnL)==0)
		//	{
		//		motor[leftTop] = -127;
		//		motor[leftMid]= -127;
		//		motor[leftBot] = -127;
		//	}
		//	off();
		//	while(SensorValue(dwnR)==0)
		//	{
		//		motor[rightTop]= 127;
		//		motor[rightMid]= 127;
		//		motor[rightBot] = 127;
		//	}
		//	off();

		////Lift Reset Manuel Assist//////
		//while(vexRT(Btn6D)==1 && SensorValue(dwnR)==0 && SensorValue(dwnL)==0)
		//{
		//	motor[leftTop] = -127;
		//	motor[leftMid]= -127;
		//	motor[leftBot] = -127;
		//	motor[rightTop]= 127;
		//	motor[rightMid]= 127;
		//	motor[rightBot] = 127;
		//}
		//off();
		//while(vexRT(Btn6D)==1 && SensorValue(dwnL)==0)
		//{
		//	motor[leftTop] = -127;
		//	motor[leftMid]= -127;
		//	motor[leftBot] = -127;
		//}
		//off();
		//while(vexRT(Btn6D)==1 && SensorValue(dwnR)==0)
		//{
		//	motor[rightTop]= 127;
		//	motor[rightMid]= 127;
		//	motor[rightBot] = 127;
		//}
		//off();

	}
	// User control code here, inside the loop

}
