#pragma config(Motor,  port1,           frontRight,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port2,           backRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           motorLeft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           motorRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



while(true)
	{
		tankControl(Ch3,Ch2);
		if(vexRT(Btn5U)==1){
	  	motor[motorLeft] = 128;
	   	motor[motorRight] = 128;
    }
    else{
  		motor[motorLeft] = 0;
  		motor[motorRight] = 0;
    }
    if(vexRT(Btn6U)==1){
    	motor[motorLeft] = -128;
    	motor[motorRight] = -128;
    }
    else{
    	motor[motorLeft] = 0;
    	motor[motorRight] = 0;
   	}




	}



}
