#pragma config(Sensor, dgtl1,  frontRight,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  frontLeft,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  backRight,      sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  backLeft,       sensorQuadEncoder)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           cTopRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           cTopLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           cMiddle,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           cBottom,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]
float ratios[4]= { 0,0,0,0};
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/*void fo()
{


	float speedfl = SensorValue[frontLeft]/time1[T1];
	float speedfr = SensorValue[frontRight]/time1[T1];
	float speedbl = SensorValue[backLeft]/time1[T1];
	float speedbr = SensorValue[backRight]/time1[T1];


}*/

//marwan i commented the code so others now whats going on
//sincerely - concernecd coder

/*float smallest() //Find Smallest Motor Speed
{
	SensorValue[frontLeft] = 0;
	SensorValue[frontRight] = 0;
	SensorValue[backLeft] = 0;
	SensorValue[backRight] = 0;
	float time = 6;
	wait1Msec(time);
	float speedfl = SensorValue[frontLeft]/time;  //Rotational Speed of each motor
	float speedfr = SensorValue[frontRight]/time;
	float speedbl = SensorValue[backLeft]/time;
	float speedbr = SensorValue[backRight]/time;
	float test[4] = {speedfl, speedfr, speedbl, speedbr};
	int smallest = speedfl;
	for(int i = 1; i < 4; i++){ //Compare each motors Speed and set smallest equal to float smallest
		if(smallest > test[i]){
			smallest = test[i];
		}
	}
	return smallest;
}

void shaftSpeedFL() // Sets speed of front left motor equal to smallest
{
	SensorValue[frontLeft] = 0;
	float time = 6;
	wait1Msec(time);
	float speedfl = SensorValue[frontLeft]/time;
	float small = smallest();
	while (speedfl<small)
	{
		 motor[frontLeft]= motor[frontLeft]-1;
	}
}

void shaftSpeedFR() // Sets speed of front right motor equal to smallest
{
	SensorValue[frontRight] = 0;
	float time = 6;
	wait1Msec(time);
	float speedfl = SensorValue[frontRight]/time;
	float small = smallest();
	while (speedfl<small)
	{
		 motor[frontRight]= motor[frontRight]-1;
	}
}

void shaftSpeedBR() // Sets speed of back right motor equal to smallest
{
	SensorValue[backRight] = 0;
	float time = 6;
	wait1Msec(time);
	float speedfl = SensorValue[backRight]/time;
	float small = smallest();
	while (speedfl<small)
	{
		 motor[backRight]= motor[backRight]-1;
	}
}

void shaftSpeedBL() // Sets speed of back left motor equal to smallest
{
	SensorValue[backLeft] = 0;
	float time = 6;
	wait1Msec(time);
	float speedfl = SensorValue[backLeft]/time;
	float small = smallest();
	while (speedfl<small)
	{
		 motor[backLeft]= motor[backLeft]-1;
	}
}*/


/*int getShaftSpeeds() //Find Smallest Motor Speed
{
	SensorValue[frontLeft] = 0;
	SensorValue[frontRight] = 0;
	SensorValue[backLeft] = 0;
	SensorValue[backRight] = 0;
	float time = 6;
	wait1Msec(time);
	float speedfl = SensorValue[frontLeft]/time;  //Rotational Speed of each motor
	float speedfr = SensorValue[frontRight]/time;
	float speedbl = SensorValue[backLeft]/time;
	float speedbr = SensorValue[backRight]/time;
	float test[4] = {speedfl, speedfr, speedbl, speedbr};
	return test;
}*/

/*void shaftSpeedFL() // Sets speed of front left motor equal to smallest
{
	SensorValue[frontLeft] = 0;
	int time = 6;
	wait1Msec(time);
	float speedfl = SensorValue[frontLeft]/time;
	float small = smallest();
	while (speedfl<small)
	{
		 motor[frontLeft]= motor[frontLeft]-1;
	}
}*/
/*
void rotateR(){          //rotate right method
	motor[frontRight]= 128;
	motor[frontLeft]=-128;
	motor[backRight]=128;
	motor[backLeft]=-128;
}

void rotateL(){        //rotate left method
	motor[frontRight]= -128;
	motor[frontLeft]=128;
	motor[backRight]=-128;
	motor[backLeft]=128;
}*/

task usercontrol()
{

	while (true)
	{

		if( vexRT[Ch1]==0 && vexRT[Ch2]==0)
			{
				//setRatios();

			}

			//Forwards and Backwords
			  motor[frontRight]=-vexRT[Ch4]+vexRT[Ch1]+vexRT[Ch3];
				motor[frontLeft]=vexRT[Ch4]+vexRT[Ch1]+vexRT[Ch3];
				motor[backLeft]=-vexRT[Ch4]-vexRT[Ch1]+vexRT[Ch3];
				motor[backRight]=vexRT[Ch4]+vexRT[Ch1]+vexRT[Ch3];
			/*
				motor[frontRight]=-vexRT[Ch4]+vexRT[Ch1]+vexRT[Ch3];
				motor[frontLeft]=vexRT[Ch4]+vexRT[Ch1]+vexRT[Ch3];
				motor[backLeft]=-vexRT[Ch4]-vexRT[Ch1]+vexRT[Ch3];
				motor[backRight]=vexRT[Ch4]+vexRT[Ch1]+vexRT[Ch3];*/

				clearTimer(T1);


	SensorValue[frontLeft] = 0;
	SensorValue[frontRight] = 0;
	SensorValue[backLeft] = 0;
	SensorValue[backRight] = 0;
	float time = 6;
	wait1Msec(time);
	float speedfl = SensorValue[frontLeft];  //Rotational Speed of each motor
	float speedfr = SensorValue[frontRight];
	float speedbl = SensorValue[backLeft];
	float speedbr = SensorValue[backRight];
	writeDebugStreamLine("speed", speedfl);
	writeDebugStreamLine("speed", speedfr);
	writeDebugStreamLine("speed", speedbl);
	writeDebugStreamLine("speed", speedbr);
	float smallest = speedfl;
	float shaftSpeeds[4] = {speedfl, speedfr, speedbl, speedbr};
	for(int i = 1; i < 4; i++){ //Compare each motors Speed and set smallest equal to float smallest
		if(smallest > shaftSpeeds[i]){
			smallest = shaftSpeeds[i];
		}
	}
	/*
	float ratios[4]= { 0,0,0,0};
	float motorSpeeds[4]= {motor[frontLeft], motor[frontRight], motor[backLeft],motor[backRight]};
	for(int i = 0; i < 4; i++){
		if(shaftSpeeds[i] != 0)
			{
				ratios[i] = motorSpeeds[i] / shaftSpeeds[i];
			}

	}
	motor[frontLeft] = smallest * ratios[0];
	motor[frontRight] = smallest * ratios[1];
	motor[backLeft] = smallest *  ratios[2];
	motor[backRight] = smallest *  ratios[3];
				*/


		if(speedfl>smallest)
			{
				motor[frontLeft]= motor[frontLeft]-1;


			}
			if(speedfr>smallest)
			{
				motor[frontRight]= motor[frontRight]-1;


			}
			if(speedbl>smallest)
			{
				motor[backLeft]= motor[backLeft]-1;


			}
			if(speedbr>smallest)
			{
				motor[backRight]= motor[backRight]-1;


			}
				if(vexRT[Btn5D]==1)
				{
					motor[cTopRight]=128;
					motor[cTopLeft]=128;
					motor[cMiddle]=128;
					motor[cBottom]=128;
				}

						//shaftSpeedBL();
						//shaftSpeedBR();
						//shaftSpeedFL();
						//shaftSpeedFR();

 // Remove this function call once you have "real" code.
	}
}
